feat: seo api
ITSeed-Official/itseed_backend pull request #19
Opened 2021-12-02 14:09 UTC by AlanSyue

# Description
Create an API for SEO use.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] see the API in stage (https://api-stage.itseed.tw/seos)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-04 05:18 UTC, Nick0603 requested changes

2021-12-04 05:18 UTC, Nick0603 commented on app/components/meta/seo.json
> +    }
We should contain more meta tag in it. Like as `og:title`, `og:description` adn `og:image`

2021-12-07 15:34 UTC, AlanSyue commented
Add following meta tag
- og:title
- og:description
- og:url
- og:image

Remove `keywords` tag

2021-12-07 15:50 UTC, Nick0603 commented on app/package.json
> -    "strapi-plugin-sentry": "^3.6.8",
Revert the adjustion

2021-12-07 15:54 UTC, Nick0603 approved these changes
LGTM

2021-12-07 15:58 UTC, merged