feat: add mentor and mentee detail
ITSeed-Official/itseed_backend pull request #20
Opened 2021-12-23 15:15 UTC by AlanSyue

# Description
1. Adjust the `mentor` component
2. Add `company` and `image_url` field

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] see in (https://api-stage.itseed.tw/careers)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-06 14:31 UTC, Nick0603 requested changes

2022-01-06 14:31 UTC, Nick0603 commented on app/extensions/documentation/documentation/1.0.0/full_documentation.json
> +          "Mentors": {
Why the variable start at upper letter?

2022-01-12 16:23 UTC, AlanSyue commented
# Summary
1. Adjust the `mentors` field into lower case
2. Add field `role` for the mentee's role, such as the leader of the information group ([ticket](https://app.asana.com/0/0/1201594493089803/f))
3. Add field `mentors_overview` for displaying the overview information about mentors. ([ticket](https://app.asana.com/0/0/1201594493089804/f))

see [API](https://api-stage.itseed.tw/careers)

2022-01-13 13:28 UTC, Nick0603 approved these changes

2022-01-13 13:29 UTC, merged