[API] Add the graduates and careers APIs
ITSeed-Official/itseed_backend pull request #3
Opened 2021-09-19 15:24 UTC by AlanSyue

# Summary
Add the following APIs
- the graduates API : to get the graduates data
- the careers API : to get the mentees' experience of the career project

# How to create the data for the test?
1. Click the `Graduates` or `Careers` button.
![image](https://user-images.githubusercontent.com/33183531/133932772-3833ca0a-5a8c-4d46-b031-f70028cf5705.png)

2. Click the `Create an entry` button.
![image](https://user-images.githubusercontent.com/33183531/133932801-cb8eb60c-a7d6-4f10-bdbc-18119e5c85d8.png)

3. You can get the careers data from [here](https://www.itseed.tw/careerList) and the graduates' data from [here](https://www.itseed.tw/careerList), then you can add the data and save it by using the GUI.
![image](https://user-images.githubusercontent.com/33183531/133932931-382ba891-20f9-4458-8ada-e099e91bc5eb.png)

4. Notice that you have to publish the data, then you can check the data by calling `http://localhost:1337/graduates` and `http://localhost:1337/careers`
![image](https://user-images.githubusercontent.com/33183531/133933017-ed681c2e-a197-40bf-8c53-cf5ff761e6c3.png)

2021-09-19 15:46 UTC, Nick0603 requested changes

2021-09-19 15:46 UTC, Nick0603 commented on app/api/careers/models/careers.settings.json
> +  }
The following UI is for careers overview. Maybe it need to define more field to satisfy it.
1. category -> e.g. 公司實習
2. overview content -> e.g. 這次專案我申請的是，盤古銀髮子品牌 — 拾夢家的社群行銷職位，主要工作為臉書的發文


![image](https://user-images.githubusercontent.com/16770691/133933538-0693ae8b-9e65-457e-9fd0-89ecaef084a6.png)

2021-09-19 15:46 UTC, Nick0603 commented on app/api/graduate/models/graduate.settings.json
> +    }
Just a idea, no need to adjust it.

If we have the the data. Maybe we can make different filter key in UI. Not just only by session.
e.g. filter by school and the result will show different session students in the school

![image](https://user-images.githubusercontent.com/16770691/133933811-45fffbe9-7883-435e-bac5-e6f924e25524.png)

2021-09-21 08:32 UTC, AlanSyue commented on app/api/graduate/models/graduate.settings.json
> +    }
Yes, it can be filtered via query string.

2021-09-21 08:33 UTC, AlanSyue commented on app/api/careers/models/careers.settings.json
> +  }
Thanks, I added the `category` and the `overview_content` fields in this commit.
https://github.com/ITSeed-Official/itseed_backend/pull/3/commits/a3574d78eb3ece9eff2c3c9bbb1f147823c77f41

2021-09-22 15:05 UTC, Nick0603 approved these changes
LGTM

2021-09-22 15:06 UTC, merged